# Generated by Django 4.1.2 on 2022-10-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer", options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.RenameField(
            model_name="customershippingaddress", old_name="contry", new_name="country",
        ),
    ]
