# Generated by Django 4.1.2 on 2022-10-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_cartitem_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartitem", name="price",),
    ]
