# Generated by Django 4.1.2 on 2022-10-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_remove_cartitem_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="contry", new_name="country",
        ),
    ]
