# Generated by Django 4.1.2 on 2022-10-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_rename_contry_customer_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
