# Generated by Django 4.1.2 on 2022-11-18 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0006_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart", options={"verbose_name_plural": "Customer Cart"},
        ),
        migrations.AlterModelOptions(
            name="cartitem", options={"verbose_name_plural": "Cart Items"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name_plural": "Customer",
            },
        ),
        migrations.AlterModelOptions(
            name="customershippingaddress",
            options={"verbose_name_plural": "Customer Shipping Address"},
        ),
        migrations.RemoveField(model_name="customer", name="email",),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
