# Generated by Django 4.1.3 on 2022-11-23 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_city_options_alter_country_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0008_remove_customer_user_customer_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDummy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_no", models.CharField(max_length=20)),
                (
                    "additional_phone_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address_line1", models.CharField(max_length=50)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("zipcode", models.CharField(max_length=10)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.city"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.country"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.state"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
