# Generated by Django 4.1.2 on 2022-11-30 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0010_customerdummy_image"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customer", options={},),
        migrations.RemoveField(model_name="customer", name="email",),
        migrations.RemoveField(model_name="customer", name="first_name",),
        migrations.RemoveField(model_name="customer", name="last_name",),
        migrations.RemoveField(model_name="customer", name="password",),
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(default=1, upload_to="customer_images"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="CustomerDummy",),
    ]
