# Generated by Django 4.1.2 on 2022-12-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_city_options_alter_country_options_and_more"),
        ("customer", "0011_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_cities",
                to="common.city",
            ),
        ),
    ]
