# Generated by Django 4.1.2 on 2022-12-07 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0013_alter_customer_city"),
    ]

    operations = [
        migrations.AlterModelOptions(name="cart", options={},),
        migrations.AlterModelOptions(name="cartitem", options={},),
    ]
