# Generated by Django 4.1.2 on 2022-10-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.TextField(null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("med", "Medicine"), ("gro", "Grocery")],
                        default="gro",
                        max_length=3,
                    ),
                ),
                ("estimated_tax", models.DecimalField(decimal_places=2, max_digits=2)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "inventory",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("image", models.ImageField(null=True, upload_to="")),
                ("status", models.BooleanField(default=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendor.vendor"
                    ),
                ),
            ],
        ),
    ]
