# Generated by Django 4.1.2 on 2022-10-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_rename_description_category_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
