# Generated by Django 4.1.2 on 2022-10-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
