# Generated by Django 4.1.2 on 2022-11-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_product_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"verbose_name_plural": "Products"},
        ),
        migrations.RemoveField(model_name="product", name="image",),
    ]
