# Generated by Django 4.1.2 on 2022-11-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_product_options_remove_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="store_category",
            field=models.CharField(
                choices=[("Medicine", "Medicine"), ("Grocery", "Grocery")],
                default="Grocery",
                max_length=10,
            ),
        ),
    ]
