# Generated by Django 4.1.3 on 2022-12-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_product_store_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=1, upload_to="product_images"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="estimated_tax",
            field=models.DecimalField(decimal_places=2, default=10.25, max_digits=4),
        ),
    ]
