# Generated by Django 4.1.2 on 2022-11-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem", options={"verbose_name_plural": "Order Items"},
        ),
        migrations.AlterModelOptions(
            name="orderstatus", options={"verbose_name_plural": "Order Status"},
        ),
    ]
