# Generated by Django 4.1.3 on 2022-12-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_orderitem_options_alter_orderstatus_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_charges",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
