# Generated by Django 4.1.4 on 2022-12-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
    ]
