insert into common_state (state_name, country_id) values ('California', 1);
insert into common_state (state_name, country_id) values ('West Virginia', 1);
insert into common_state (state_name, country_id) values ('Virginia', 1);
insert into common_state (state_name, country_id) values ('Massachusetts', 1);
insert into common_state (state_name, country_id) values ('Iowa', 1);
insert into common_state (state_name, country_id) values ('Louisiana', 1);
insert into common_state (state_name, country_id) values ('Illinois', 1);
insert into common_state (state_name, country_id) values ('New Mexico', 1);
insert into common_state (state_name, country_id) values ('New York', 1);
insert into common_state (state_name, country_id) values ('Michigan', 1);
insert into common_state (state_name, country_id) values ('Louisiana', 1);
insert into common_state (state_name, country_id) values ('Maryland', 1);
insert into common_state (state_name, country_id) values ('Florida', 1);
insert into common_state (state_name, country_id) values ('Texas', 1);
insert into common_state (state_name, country_id) values ('Michigan', 1);
insert into common_state (state_name, country_id) values ('Kansas', 1);
insert into common_state (state_name, country_id) values ('Washington', 1);
insert into common_state (state_name, country_id) values ('Pennsylvania', 1);
insert into common_state (state_name, country_id) values ('Florida', 1);
insert into common_state (state_name, country_id) values ('California', 1);
insert into common_state (state_name, country_id) values ('Ohio', 1);
insert into common_state (state_name, country_id) values ('Hawaii', 1);
insert into common_state (state_name, country_id) values ('District of Columbia', 1);
insert into common_state (state_name, country_id) values ('North Dakota', 1);
insert into common_state (state_name, country_id) values ('New York', 1);
insert into common_state (state_name, country_id) values ('Tennessee', 1);
insert into common_state (state_name, country_id) values ('Kentucky', 1);
insert into common_state (state_name, country_id) values ('Utah', 1);
insert into common_state (state_name, country_id) values ('Texas', 1);
insert into common_state (state_name, country_id) values ('North Carolina', 1);
insert into common_state (state_name, country_id) values ('Florida', 1);
insert into common_state (state_name, country_id) values ('Texas', 1);
insert into common_state (state_name, country_id) values ('South Carolina', 1);
insert into common_state (state_name, country_id) values ('Massachusetts', 1);
insert into common_state (state_name, country_id) values ('Florida', 1);
insert into common_state (state_name, country_id) values ('North Carolina', 1);
insert into common_state (state_name, country_id) values ('Missouri', 1);
insert into common_state (state_name, country_id) values ('New Jersey', 1);
insert into common_state (state_name, country_id) values ('Colorado', 1);
insert into common_state (state_name, country_id) values ('Georgia', 1);